version: "3.9"
services:
  mysql8.3.0:
    container_name: mysql8.3.0
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres16:
    container_name: postgres16 
    image: postgres:16-alpine
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgresql:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  msvc-usuarios:
    container_name: msvc-usuarios
    build:
      context: ./
      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./msvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8.3.0
    restart: always
  msvc-cursos: 
    container_name: msvc-cursos
    build:
      context: ./
      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file: 
      - ./msvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres16
      - msvc-usuarios
    restart: always        
volumes:
  data-mysql:
    name: data-mysql
    external: true
  data-postgresql:
    name: data-postgresql
    external: true
networks:
  spring:
    